name: CI/CD for Go-Fiber with GHCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Container Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: ${{ secrets.IMAGE_NAME }}
          push: ${{ github.ref_name == 'master' }}

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ${{ secrets.IMAGE_NAME }}
            docker compose down
            docker compose up -d --build
            docker images | grep '${{ secrets.IMAGE_NAME }}' | grep '<none>' | awk '{print $3}' | xargs --no-run-if-empty docker rmi